"""add shop address to setting

Revision ID: 5a18ac4fb67d
Revises: bd737bd81c42
Create Date: 2026-08-17 16:43:50.266064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a18ac4fb67d'
down_revision: Union[str, Sequence[str], None] = 'bd737bd81c42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('setting', sa.Column('shop_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('setting', 'shop_address')
    # ### end Alembic commands ###
