"""add_sales

Revision ID: f5f369972f38
Revises: 9e832fe54b29
Create Date: 2026-08-08 16:49:43.831318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5f369972f38'
down_revision: Union[str, Sequence[str], None] = '9e832fe54b29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['party.id'], name=op.f('sales_order_party_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sales_order_pkey'))
    )
    op.create_index(op.f('sales_order_party_id_idx'), 'sales_order', ['party_id'], unique=False)
    op.create_table('sales_order_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_order_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rate_pkr', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name=op.f('sales_order_line_item_id_fkey')),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_order.id'], name=op.f('sales_order_line_sales_order_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sales_order_line_pkey'))
    )
    op.create_index(op.f('sales_order_line_item_id_idx'), 'sales_order_line', ['item_id'], unique=False)
    op.create_index(op.f('sales_order_line_sales_order_id_idx'), 'sales_order_line', ['sales_order_id'], unique=False)
    op.create_table('sales_order_line_lot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_order_line_id', sa.Integer(), nullable=False),
    sa.Column('stock_lot_id', sa.Integer(), nullable=False),
    sa.Column('qty_consumed', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_cost_pkr', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sales_order_line_id'], ['sales_order_line.id'], name=op.f('sales_order_line_lot_sales_order_line_id_fkey')),
    sa.ForeignKeyConstraint(['stock_lot_id'], ['stock_lot.id'], name=op.f('sales_order_line_lot_stock_lot_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sales_order_line_lot_pkey'))
    )
    op.create_index(op.f('sales_order_line_lot_sales_order_line_id_idx'), 'sales_order_line_lot', ['sales_order_line_id'], unique=False)
    op.create_index(op.f('sales_order_line_lot_stock_lot_id_idx'), 'sales_order_line_lot', ['stock_lot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('sales_order_line_lot_stock_lot_id_idx'), table_name='sales_order_line_lot')
    op.drop_index(op.f('sales_order_line_lot_sales_order_line_id_idx'), table_name='sales_order_line_lot')
    op.drop_table('sales_order_line_lot')
    op.drop_index(op.f('sales_order_line_sales_order_id_idx'), table_name='sales_order_line')
    op.drop_index(op.f('sales_order_line_item_id_idx'), table_name='sales_order_line')
    op.drop_table('sales_order_line')
    op.drop_index(op.f('sales_order_party_id_idx'), table_name='sales_order')
    op.drop_table('sales_order')
    # ### end Alembic commands ###
