"""add cargo shipment and landed cost

Revision ID: 5dda19e57a70
Revises: c51635a781db
Create Date: 2026-08-07 22:25:09.790896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dda19e57a70'
down_revision: Union[str, Sequence[str], None] = 'c51635a781db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargo_cost_basis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('cargo_cost_basis_pkey')),
    sa.UniqueConstraint('code', name=op.f('cargo_cost_basis_code_key')),
    sa.UniqueConstraint('name', name=op.f('cargo_cost_basis_name_key'))
    )
    op.create_table('cargo_mode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('cargo_mode_pkey')),
    sa.UniqueConstraint('name', name=op.f('cargo_mode_name_key'))
    )
    op.create_table('cargo_shipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cargo_agent_id', sa.Integer(), nullable=False),
    sa.Column('cargo_mode_id', sa.Integer(), nullable=False),
    sa.Column('cost_basis_id', sa.Integer(), nullable=False),
    sa.Column('shipment_date', sa.Date(), nullable=False),
    sa.Column('total_cost_pkr', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cargo_agent_id'], ['party.id'], name=op.f('cargo_shipment_cargo_agent_id_fkey')),
    sa.ForeignKeyConstraint(['cargo_mode_id'], ['cargo_mode.id'], name=op.f('cargo_shipment_cargo_mode_id_fkey')),
    sa.ForeignKeyConstraint(['cost_basis_id'], ['cargo_cost_basis.id'], name=op.f('cargo_shipment_cost_basis_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cargo_shipment_pkey'))
    )
    op.create_index(op.f('cargo_shipment_cargo_agent_id_idx'), 'cargo_shipment', ['cargo_agent_id'], unique=False)
    op.create_index(op.f('cargo_shipment_cargo_mode_id_idx'), 'cargo_shipment', ['cargo_mode_id'], unique=False)
    op.create_index(op.f('cargo_shipment_cost_basis_id_idx'), 'cargo_shipment', ['cost_basis_id'], unique=False)
    op.create_table('cargo_allocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cargo_shipment_id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_line_id', sa.Integer(), nullable=False),
    sa.Column('basis_value', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('allocated_cost_pkr', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cargo_shipment_id'], ['cargo_shipment.id'], name=op.f('cargo_allocation_cargo_shipment_id_fkey')),
    sa.ForeignKeyConstraint(['purchase_order_line_id'], ['purchase_order_line.id'], name=op.f('cargo_allocation_purchase_order_line_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cargo_allocation_pkey'))
    )
    op.create_index(op.f('cargo_allocation_cargo_shipment_id_idx'), 'cargo_allocation', ['cargo_shipment_id'], unique=False)
    op.create_index(op.f('cargo_allocation_purchase_order_line_id_idx'), 'cargo_allocation', ['purchase_order_line_id'], unique=True)
    op.add_column('purchase_order_line', sa.Column('landed_cost_pkr', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_order_line', 'landed_cost_pkr')
    op.drop_index(op.f('cargo_allocation_purchase_order_line_id_idx'), table_name='cargo_allocation')
    op.drop_index(op.f('cargo_allocation_cargo_shipment_id_idx'), table_name='cargo_allocation')
    op.drop_table('cargo_allocation')
    op.drop_index(op.f('cargo_shipment_cost_basis_id_idx'), table_name='cargo_shipment')
    op.drop_index(op.f('cargo_shipment_cargo_mode_id_idx'), table_name='cargo_shipment')
    op.drop_index(op.f('cargo_shipment_cargo_agent_id_idx'), table_name='cargo_shipment')
    op.drop_table('cargo_shipment')
    op.drop_table('cargo_mode')
    op.drop_table('cargo_cost_basis')
    # ### end Alembic commands ###
