"""add_expenses

Revision ID: aa6c8f189438
Revises: b7a2e491f3c8
Create Date: 2026-08-10 16:00:27.662900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa6c8f189438'
down_revision: Union[str, Sequence[str], None] = 'b7a2e491f3c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('expense_category_pkey')),
    sa.UniqueConstraint('name', name=op.f('expense_category_name_key'))
    )
    op.create_table('recurring_expense_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('payment_account_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['expense_category.id'], name=op.f('recurring_expense_template_category_id_fkey')),
    sa.ForeignKeyConstraint(['payment_account_id'], ['payment_account.id'], name=op.f('recurring_expense_template_payment_account_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('recurring_expense_template_pkey'))
    )
    op.create_index(op.f('recurring_expense_template_category_id_idx'), 'recurring_expense_template', ['category_id'], unique=False)
    op.create_index(op.f('recurring_expense_template_payment_account_id_idx'), 'recurring_expense_template', ['payment_account_id'], unique=False)
    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('payment_account_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('recurring_template_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['expense_category.id'], name=op.f('expense_category_id_fkey')),
    sa.ForeignKeyConstraint(['payment_account_id'], ['payment_account.id'], name=op.f('expense_payment_account_id_fkey')),
    sa.ForeignKeyConstraint(['recurring_template_id'], ['recurring_expense_template.id'], name=op.f('expense_recurring_template_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('expense_pkey'))
    )
    op.create_index(op.f('expense_category_id_idx'), 'expense', ['category_id'], unique=False)
    op.create_index(op.f('expense_payment_account_id_idx'), 'expense', ['payment_account_id'], unique=False)
    op.create_index(op.f('expense_recurring_template_id_idx'), 'expense', ['recurring_template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('expense_recurring_template_id_idx'), table_name='expense')
    op.drop_index(op.f('expense_payment_account_id_idx'), table_name='expense')
    op.drop_index(op.f('expense_category_id_idx'), table_name='expense')
    op.drop_table('expense')
    op.drop_index(op.f('recurring_expense_template_payment_account_id_idx'), table_name='recurring_expense_template')
    op.drop_index(op.f('recurring_expense_template_category_id_idx'), table_name='recurring_expense_template')
    op.drop_table('recurring_expense_template')
    op.drop_table('expense_category')
    # ### end Alembic commands ###
