"""add item compatible model

Revision ID: 53defd1e1c78
Revises: a307efeb3de2
Create Date: 2026-08-16 22:48:34.435688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53defd1e1c78'
down_revision: Union[str, Sequence[str], None] = 'a307efeb3de2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_compatible_model',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name=op.f('item_compatible_model_item_id_fkey')),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], name=op.f('item_compatible_model_model_id_fkey')),
    sa.PrimaryKeyConstraint('item_id', 'model_id', name=op.f('item_compatible_model_pkey'))
    )
    op.create_index(op.f('item_compatible_model_model_id_idx'), 'item_compatible_model', ['model_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('item_compatible_model_model_id_idx'), table_name='item_compatible_model')
    op.drop_table('item_compatible_model')
    # ### end Alembic commands ###
