"""add inventory

Revision ID: 9e832fe54b29
Revises: 5dda19e57a70
Create Date: 2026-08-08 02:53:42.538118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e832fe54b29'
down_revision: Union[str, Sequence[str], None] = '5dda19e57a70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_lot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_line_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('qty_received', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('qty_remaining', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('landed_cost_pkr', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name=op.f('stock_lot_item_id_fkey')),
    sa.ForeignKeyConstraint(['purchase_order_line_id'], ['purchase_order_line.id'], name=op.f('stock_lot_purchase_order_line_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('stock_lot_pkey'))
    )
    op.create_index(op.f('stock_lot_item_id_idx'), 'stock_lot', ['item_id'], unique=False)
    op.create_index(op.f('stock_lot_purchase_order_line_id_idx'), 'stock_lot', ['purchase_order_line_id'], unique=True)
    op.create_table('stock_movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_lot_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(), nullable=False),
    sa.Column('qty_delta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('movement_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_lot_id'], ['stock_lot.id'], name=op.f('stock_movement_stock_lot_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('stock_movement_pkey'))
    )
    op.create_index(op.f('stock_movement_stock_lot_id_idx'), 'stock_movement', ['stock_lot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('stock_movement_stock_lot_id_idx'), table_name='stock_movement')
    op.drop_table('stock_movement')
    op.drop_index(op.f('stock_lot_purchase_order_line_id_idx'), table_name='stock_lot')
    op.drop_index(op.f('stock_lot_item_id_idx'), table_name='stock_lot')
    op.drop_table('stock_lot')
    # ### end Alembic commands ###
