"""add catalog, party, purchasing

Revision ID: c51635a781db
Revises: f068fd4e99af
Create Date: 2026-08-07 19:00:57.937646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c51635a781db'
down_revision: Union[str, Sequence[str], None] = 'f068fd4e99af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('category_pkey')),
    sa.UniqueConstraint('name', name=op.f('category_name_key'))
    )
    op.create_table('model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('model_pkey')),
    sa.UniqueConstraint('name', name=op.f('model_name_key'))
    )
    op.create_table('party',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('roles', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('party_pkey'))
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('variant', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('item_category_id_fkey')),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], name=op.f('item_model_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('item_pkey')),
    sa.UniqueConstraint('sku', name=op.f('item_sku_key'))
    )
    op.create_index(op.f('item_category_id_idx'), 'item', ['category_id'], unique=False)
    op.create_index(op.f('item_model_id_idx'), 'item', ['model_id'], unique=False)
    op.create_table('purchase_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['party.id'], name=op.f('purchase_order_party_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('purchase_order_pkey'))
    )
    op.create_index(op.f('purchase_order_party_id_idx'), 'purchase_order', ['party_id'], unique=False)
    op.create_table('purchase_order_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rate_rmb', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rate_pkr', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name=op.f('purchase_order_line_item_id_fkey')),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], name=op.f('purchase_order_line_purchase_order_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('purchase_order_line_pkey'))
    )
    op.create_index(op.f('purchase_order_line_item_id_idx'), 'purchase_order_line', ['item_id'], unique=False)
    op.create_index(op.f('purchase_order_line_purchase_order_id_idx'), 'purchase_order_line', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ledger_entry_party_id_idx'), 'ledger_entry', ['party_id'], unique=False)
    op.create_foreign_key(op.f('ledger_entry_party_id_fkey'), 'ledger_entry', 'party', ['party_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ledger_entry_party_id_fkey'), 'ledger_entry', type_='foreignkey')
    op.drop_index(op.f('ledger_entry_party_id_idx'), table_name='ledger_entry')
    op.drop_index(op.f('purchase_order_line_purchase_order_id_idx'), table_name='purchase_order_line')
    op.drop_index(op.f('purchase_order_line_item_id_idx'), table_name='purchase_order_line')
    op.drop_table('purchase_order_line')
    op.drop_index(op.f('purchase_order_party_id_idx'), table_name='purchase_order')
    op.drop_table('purchase_order')
    op.drop_index(op.f('item_model_id_idx'), table_name='item')
    op.drop_index(op.f('item_category_id_idx'), table_name='item')
    op.drop_table('item')
    op.drop_table('party')
    op.drop_table('model')
    op.drop_table('category')
    # ### end Alembic commands ###
