"""add_brand

Revision ID: a307efeb3de2
Revises: aa6c8f189438
Create Date: 2026-08-11 17:20:41.888574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a307efeb3de2'
down_revision: Union[str, Sequence[str], None] = 'aa6c8f189438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('brand_pkey')),
    sa.UniqueConstraint('name', name=op.f('brand_name_key'))
    )

    # brand_id starts nullable so existing model rows (if any) don't break the
    # add-column step; every existing row is backfilled onto a placeholder brand
    # below, then the column is locked to NOT NULL. Re-assign the real brand for
    # any backfilled rows afterward via the Catalog screen.
    op.add_column('model', sa.Column('brand_id', sa.Integer(), nullable=True))

    brand = sa.table('brand', sa.column('id', sa.Integer), sa.column('name', sa.String), sa.column('is_active', sa.Boolean))
    conn = op.get_bind()
    existing_model_count = conn.execute(sa.text("SELECT count(*) FROM model")).scalar()
    if existing_model_count:
        placeholder_id = conn.execute(
            brand.insert().values(name="Unspecified", is_active=True).returning(brand.c.id)
        ).scalar()
        conn.execute(sa.text("UPDATE model SET brand_id = :bid WHERE brand_id IS NULL"), {"bid": placeholder_id})

    op.alter_column('model', 'brand_id', nullable=False)
    op.drop_constraint(op.f('model_name_key'), 'model', type_='unique')
    op.create_index(op.f('model_brand_id_idx'), 'model', ['brand_id'], unique=False)
    op.create_unique_constraint(op.f('model_brand_id_key'), 'model', ['brand_id', 'name'])
    op.create_foreign_key(op.f('model_brand_id_fkey'), 'model', 'brand', ['brand_id'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('model_brand_id_fkey'), 'model', type_='foreignkey')
    op.drop_constraint(op.f('model_brand_id_key'), 'model', type_='unique')
    op.drop_index(op.f('model_brand_id_idx'), table_name='model')
    op.create_unique_constraint(op.f('model_name_key'), 'model', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('model', 'brand_id')
    op.drop_table('brand')
    # ### end Alembic commands ###
